import React from 'react';
import {
  Armchair,
  ArrowLeft,
  ArrowRight,
  Bell,
  BrushCleaning,
  CalendarDays,
  Camera,
  ChartColumn,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleCheck,
  CircleHelp,
  CirclePlus,
  ClipboardList,
  Clock,
  Droplet,
  Ellipsis,
  FileText,
  FolderOpen,
  Hourglass,
  House,
  IdCard,
  Image,
  Landmark,
  Laptop,
  LayoutDashboard,
  LogOut,
  Mail,
  MapPin,
  Pencil,
  Plug,
  ReceiptText,
  Search,
  Settings,
  UserRound,
  Wrench,
} from 'lucide-react-native';
import { colors } from '../theme';
const icons = {
  Armchair,
  ArrowLeft,
  ArrowRight,
  Bell,
  BrushCleaning,
  CalendarDays,
  Camera,
  ChartColumn,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleCheck,
  CircleHelp,
  CirclePlus,
  ClipboardList,
  Clock,
  Droplet,
  Ellipsis,
  FileText,
  FolderOpen,
  Hourglass,
  House,
  IdCard,
  Image,
  Landmark,
  Laptop,
  LayoutDashboard,
  LogOut,
  Mail,
  MapPin,
  Pencil,
  Plug,
  ReceiptText,
  Search,
  Settings,
  UserRound,
  Wrench,
};
/** Consistent vector icons throughout the app. */
export default function AppIcon({
  name,
  size = 22,
  color = colors.primary,
}: {
  name: string;
  size?: number;
  color?: string;
}) {
  const Icon = icons[name as keyof typeof icons] ?? FileText;
  return (
    <Icon size={size} color={color} strokeWidth={1.8} accessible={false} />
  );
}
